// <auto-generated />
namespace DoTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Developers_Tasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Developers_Tasks));
        
        string IMigrationMetadata.Id
        {
            get { return "202012030033206_Developers_Tasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
